
#ifndef _GUIFRAME_
#define _GUIFRAME_

/**
@file
Subclass of frame, which is generated by wxFormBuilder.
*/

#include <iostream>
#include <string>
#include <dos.h>
#include <windows.h>
#include "gui.h"
#include "histogram.hpp"
#include "sounfile.h"
#include <wx/filedlg.h> //wxFileDialog
#include <wx/msgdlg.h>
#include <opencv2/core.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/videoio.hpp>
 
//// end generated include



/** Clase Guiframe, deriva de la clase GUI, de la que recibe las pautas para generar la vista */
class guiframe : public gui
{
	protected:
		//Manejadores para eventos de la clase GUI
		void onSlider( wxCommandEvent& event );
		void exit( wxCommandEvent& event );
		void abrir_video( wxCommandEvent& event );
		void play( wxCommandEvent& event ); 
		void onTimer(wxTimerEvent& event); 
		void updateFPS(wxSpinEvent& event);
		void updateCut(wxSpinEvent& event);
	public:
		/** Constructor */
		guiframe( wxWindow* parent );
	//// end generated class members
private:
	wxTimer timer;
	const wxString PLAY = "Play"; 
	const wxString PAUSE = "Pause";
	bool video_paused = true;
	cv::VideoCapture cam;  //variable donde se guarda el video a procesar
	SoundFile snd;
	histogram hgm;
	//int fps = 40; 
	int cutSnd = 10;
	int timervalue = 25;
	/*Numero de frame actual*/
	const int NFRAME = cv::CAP_PROP_POS_FRAMES;
	//Numero de frames del video
	const int FRAMES = cv::CAP_PROP_FRAME_COUNT;
	//Frames por segundo
	const int CVFPS    = cv::CAP_PROP_FPS;
	DECLARE_EVENT_TABLE()



};

#endif // __guiframe__
